# Use the official MySQL image as the base image
FROM mysql:latest

# Set environment variables for MySQL
ENV MYSQL_DATABASE: db
ENV MYSQL_PASSWORD: root
ENV MYSQL_ROOT_PASSWORD: root
ENV MYSQL_PORT: 3306

EXPOSE 3306